-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 10:39:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ingresoCovid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ingresoCovid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ingresoCovid` DEFAULT CHARACTER SET utf8 ;
USE `ingresoCovid`;

-- -----------------------------------------------------
-- Table `ingresoCovid`.`OcupacionSede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingresoCovid`.`ocupacionSede` (
  `idSede` INT NOT NULL AUTO_INCREMENT,
  `nombreSede` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `ocupacionReal` INT NULL,
  PRIMARY KEY (`idSede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingresoCovid`.`registroUnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingresoCovid`.`registroUnico` (
  `cedulaUsuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono1` VARCHAR(45) NOT NULL,
  `telefono2` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `tipoDocumento` VARCHAR(45) NOT NULL,
  `eps` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedulaUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingresoCovid`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingresoCovid`.`ingresos` (
  `idingresos` INT NOT NULL AUTO_INCREMENT,
  `temparatura` VARCHAR(45) NOT NULL,
  `OcupacionSede_idSede` INT NOT NULL,
  `registroUnico_cedulaUsuario` VARCHAR(45) NOT NULL,
  `horaIngreso` TIME NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `horaSalida` TIME NULL,
  `fechaSalida` DATE NULL,
  PRIMARY KEY (`idingresos`, `OcupacionSede_idSede`, `registroUnico_cedulaUsuario`),
  INDEX `fk_ingresos_OcupacionSede_idx` (`OcupacionSede_idSede` ASC) ,
  INDEX `fk_ingresos_registroUnico1_idx` (`registroUnico_cedulaUsuario` ASC),
  CONSTRAINT `fk_ingresos_OcupacionSede`
    FOREIGN KEY (`OcupacionSede_idSede`)
    REFERENCES `ingresoCovid`.`OcupacionSede` (`idSede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_registroUnico1`
    FOREIGN KEY (`registroUnico_cedulaUsuario`)
    REFERENCES `ingresoCovid`.`registroUnico` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE ingresos
ADD FOREIGN KEY (ocupacionSede_idSede) REFERENCES ocupacionSede(idSede);
ALTER TABLE ingresos
ADD FOREIGN KEY (registroUnico_cedulaUsuario) REFERENCES registroUnico(cedulaUsuario);


-- -----------------------------------------------------
-- Table `ingresoCovid`.`registroDiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingresoCovid`.`registroDiario` (
  `idregistroDiario` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `temperatura` VARCHAR(45) NOT NULL,
  `pregunta1` VARCHAR(45) NOT NULL,
  `pregunta2` VARCHAR(45) NOT NULL,
  `pregunta3` VARCHAR(45) NOT NULL,
  `pregunta4` VARCHAR(45) NULL,
  `autorizacion` VARCHAR(45) NULL,
  `registroUnico_cedulaUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregistroDiario`, `registroUnico_cedulaUsuario`),
  INDEX `fk_registroDiario_registroUnico1_idx` (`registroUnico_cedulaUsuario` ASC),
  CONSTRAINT `fk_registroDiario_registroUnico1`
    FOREIGN KEY (`registroUnico_cedulaUsuario`)
    REFERENCES `ingresoCovid`.`registroUnico` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
